sonar.projectKey=Insaner1980_Corners_Apart_Android
sonar.organization=insaner1980
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java

sonar.exclusions=**/build/**,**/generated/**
sonar.cpd.exclusions=**/build/**,**/generated/**

sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoDebugUnitTestReport/jacocoDebugUnitTestReport.xml
sonar.coverage.exclusions=**/build/**,**/generated/**,app/src/main/java/com/finnvek/cornersapart/App.kt,app/src/main/java/com/finnvek/cornersapart/MainActivity.kt,app/src/main/java/com/finnvek/cornersapart/ui/screens/**,app/src/main/java/com/finnvek/cornersapart/multiplayer/PlayServicesConnectionsClientFacade.kt
